---
fediscoverer_hostname: search.3dprint.social
fediscoverer_secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61623330323034343333383163386637663364326130626538366164396438396164306636343061
          3761333635646666633837343331393963656663613938360a323233343763633763383762393462
          34396633623434316330326664376438356264623734653463336232633431383866363630393933
          6338396366313639620a323565653036303735636131386134393233363662353036666238326233
          34653461363139393964373335376665333331356232653264323264623364313331346261383539
          66613739623936613566383631303366623032393434306564303465353239663039646330643861
          356436336631353636633030326633383736
fediscoverer_contact_email: james@floppy.org.uk
fediscoverer_fediverse_account: "@manyfold@3dp.chat"
